### ISSUE TITLE
Various console warnings/errors when in a cross-world party

### ISSUE THREAD

**Issue by valarnin** [Zeffuro/ZeffUI#16] opened 2021-02-19 02:18 UTC
When in a cross-world party, various console errors are triggered. Here are a small sample.

```
Info: Zeff: BrowserConsole: Uncaught TypeError: Cannot read property 'job' of undefined (Source: https://zeffuro.github.io/ZeffUI/scripts/index.js, Line: 840)
Info: Zeff: BrowserConsole: Uncaught TypeError: Cannot read property 'name' of undefined (Source: https://zeffuro.github.io/ZeffUI/scripts/index.js, Line: 1596)
Info: Zeff: BrowserConsole: Uncaught TypeError: Cannot read property 'name' of undefined (Source: https://zeffuro.github.io/ZeffUI/scripts/index.js, Line: 1510)
Info: Zeff: BrowserConsole: Uncaught TypeError: Cannot read property 'name' of undefined (Source: https://zeffuro.github.io/ZeffUI/scripts/index.js, Line: 1653)
```

Looking through the .js file I don't really see how this can happen but it happens pretty often for me.

**Comment by Zeffuro** [comment] 2021-02-21 16:10
Yeah I think I found it, this happens after you exit the instance and onPartyChanged get's called a bunch then you're techically in an empty party.

      index.js:1706 [onPartyChanged]
      index.js:1706 {type: "PartyChanged", party: Array(0)}
      index.js:1706 [GeneratePartyList]
      index.js:1706 []
      index.js:853 Uncaught TypeError: Cannot read property 'job' of undefined
          at index.js:853
          at Array.filter (<anonymous>)
          at generateRaidBuffs (index.js:853)
          at generatePartyList (index.js:966)
          at onPartyChanged (index.js:1447)
          at index.js:57
          at a (common.min.js:1)
          at <anonymous>:1:30
      (anonymous) @ index.js:853
      generateRaidBuffs @ index.js:853
      generatePartyList @ index.js:966
      onPartyChanged @ index.js:1447
      (anonymous) @ index.js:57
      a @ common.min.js:1
      (anonymous) @ VM181498:1

I've made changes that should work but I still need to test them.

**Comment by Zeffuro** [comment] 2021-02-24 21:53
I have done a good chunk of BLU content over the last days and have not had the error anymore, I think I can confidently say the issue is fixed so I'm closing the issue.

**Closed by Zeffuro** 2021-02-24 21:53 UTC
