### ISSUE TITLE
Sometimes UI is unresponsive

### ISSUE THREAD

**Issue by mooondark** [Zeffuro/ZeffUI#5] opened 2020-12-27 17:41 UTC
Hello,
When I change to another instance, the UI (mainly the mitigation part) is not working.
If I reload the overlay, I get this error :
```
[27/12/2020 18:27:57] Info: DFA: ZoneChanged: 897, Cinder Drift
[27/12/2020 18:33:48] Info: ZeffUI: BrowserConsole: Uncaught TypeError: Cannot read property 'level' of null (Source: https://zeffuro.github.io/ZeffUI/, Line: 505)
[27/12/2020 18:33:48] Info: ZeffUI: BrowserConsole: ZeffUI fully loaded. (Source: https://zeffuro.github.io/ZeffUI/, Line: 285)
[27/12/2020 18:33:57] Info: ZeffUI: BrowserConsole: Uncaught TypeError: Cannot read property 'level' of null (Source: https://zeffuro.github.io/ZeffUI/, Line: 505)
[27/12/2020 18:33:57] Info: ZeffUI: BrowserConsole: ZeffUI fully loaded. (Source: https://zeffuro.github.io/ZeffUI/, Line: 285)
```

**Comment by Zeffuro** [comment] 2020-12-27 19:35
Hmm I wonder if this has to do with ACT being overloaded/busy in general.
Lots of people have issues with the CPU.

You might get those errors on reload if you're reloading while in combat (because it needs information you get as soon as you move around after loading the overlay. Will need to test and check it out more.

Can you export your settings and drop it here from the settings? Want to see if there's anything different.

**Comment by mooondark** [comment] 2020-12-27 20:01
Yeah sure, here's my settings :
`eyJza2luIjoibWF0ZXJpYWwtZGFyayIsImxhbmd1YWdlIjoiZW4iLCJmb250IjoiQXJpYWwiLCJvdmVycmlkZSI6eyJlbmFibGVkIjpmYWxzZSwiYWJpbGl0aWVzIjpbXX0sImhlYWx0aGJhciI6eyJlbmFibGVkIjpmYWxzZSwiaGlkZW91dG9mY29tYmF0IjpmYWxzZSwidGV4dGVuYWJsZWQiOnRydWUsImNvbG9yIjoiLS1maWx0ZXItZGFyay1ncmVlbiIsInNjYWxlIjoiMSIsInJvdGF0aW9uIjoiMCIsIngiOjAsInkiOjIxNiwiZm9udCI6IkFyaWFsIn0sIm1hbmFiYXIiOnsiZW5hYmxlZCI6ZmFsc2UsImhpZGVvdXRvZmNvbWJhdCI6ZmFsc2UsInRleHRlbmFibGVkIjp0cnVlLCJjb2xvciI6Ii0tZmlsdGVyLWxpZ2h0LXBpbmsiLCJzY2FsZSI6IjEiLCJyb3RhdGlvbiI6IjAiLCJ4IjowLCJ5IjoyMzIsImZvbnQiOiJBcmlhbCJ9LCJ0aW1lcmJhciI6eyJlbmFibGVkIjpmYWxzZSwidGV4dGVuYWJsZWQiOnRydWUsImNvbG9yIjoiLS1maWx0ZXItZGFyay1yZWQiLCJzY2FsZSI6IjEiLCJyb3RhdGlvbiI6IjAiLCJ4Ijo1NjYsInkiOjIyLCJmb250IjoiQXJpYWwifSwiZG90dGltZXJiYXIiOnsiZW5hYmxlZCI6dHJ1ZSwiaGlkZW91dG9mY29tYmF0IjpmYWxzZSwiaGlkZXdoZW5kcm9wcGVkb2ZmIjpmYWxzZSwidGV4dGVuYWJsZWQiOmZhbHNlLCJ0dHNlbmFibGVkIjpmYWxzZSwiaW1hZ2VlbmFibGVkIjp0cnVlLCJtdWx0aWRvdGVuYWJsZWQiOmZhbHNlLCJncm93ZGlyZWN0aW9uIjoiMSIsInBhZGRpbmciOiIyMCIsInNjYWxlIjoiMSIsInJvdGF0aW9uIjoiMCIsIngiOjExNzAsInkiOjYyNCwiZm9udCI6IkFyaWFsIn0sImJ1ZmZ0aW1lcmJhciI6eyJlbmFibGVkIjp0cnVlLCJoaWRlb3V0b2Zjb21iYXQiOmZhbHNlLCJoaWRld2hlbmRyb3BwZWRvZmYiOmZhbHNlLCJ0ZXh0ZW5hYmxlZCI6ZmFsc2UsInR0c2VuYWJsZWQiOmZhbHNlLCJpbWFnZWVuYWJsZWQiOnRydWUsImdyb3dkaXJlY3Rpb24iOiIxIiwicGFkZGluZyI6IjIwIiwic2NhbGUiOiIxIiwicm90YXRpb24iOiIwIiwieCI6MTE3MSwieSI6Njc1LCJmb250IjoiQXJpYWwifSwic3RhY2tzYmFyIjp7ImVuYWJsZWQiOnRydWUsImhpZGVvdXRvZmNvbWJhdCI6ZmFsc2UsImNvbG9yIjoiLS1maWx0ZXItYnJpZ2h0LXJlZCIsInNjYWxlIjoiMSIsIngiOjAsInkiOjE3MH0sInJhaWRidWZmcyI6eyJlbmFibGVkIjpmYWxzZSwidHRzZW5hYmxlZCI6ZmFsc2UsImhpZGVvdXRvZmNvbWJhdCI6ZmFsc2UsImhpZGV3aGVuc29sbyI6ZmFsc2UsImFsd2F5c3Nob3ciOnRydWUsImdyb3dsZWZ0IjpmYWxzZSwiY29sdW1ucyI6IjgiLCJwYWRkaW5nIjoiNSIsInNjYWxlIjoiMSIsIngiOjAsInkiOjI0OCwiZm9udCI6IkFyaWFsIn0sIm1pdGlnYXRpb24iOnsiZW5hYmxlZCI6dHJ1ZSwidHRzZW5hYmxlZCI6ZmFsc2UsImhpZGVvdXRvZmNvbWJhdCI6ZmFsc2UsImhpZGV3aGVuc29sbyI6ZmFsc2UsImFsd2F5c3Nob3ciOnRydWUsImdyb3dsZWZ0IjpmYWxzZSwiY29sdW1ucyI6IjIiLCJwYWRkaW5nIjoiMCIsInNjYWxlIjoiMS4xIiwieCI6Nzk3LCJ5Ijo1MTYsImZvbnQiOiJBcmlhbCJ9fQ==`

Another thing, not related (tell me if I need to open a new issue) : even if Pullbar is off, it is always displayed (I use the one from cactbot).

**Comment by Zeffuro** [comment] 2020-12-27 20:07
Yeah if you also use jobs ui from cactbot, ZeffUI is unrelated to those settings. Only reason why you need cactbot atm is for the memory reading from the cactbot plugin.
Can probably turn it off in jobs ui settings somewhere but not sure where.

**Comment by Zeffuro** [comment] 2021-01-30 10:46
Has anything changed recently?
I'm still suspecting the issue came from other sources and not ZeffUI itself.

**Comment by Zeffuro** [comment] 2021-02-14 23:37
Going to close this issue for the time being. You can reopen this if needed but I don't think ZeffUI is the cause of the unresponsiveness.

**Closed by Zeffuro** 2021-02-14 23:37 UTC
